version: '2'
services:
  gw:
    image: prom/statsd-exporter
    ports:
      - "9876:9125/udp"
      - "9102:9102"
    volumes:
      - "./statsd_mapping.conf:/tmp/statsd_mapping.conf"
    command: [-statsd.mapping-config=/tmp/statsd_mapping.conf]
  prom:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/prometheus-data/prometheus.yml"
    command: [-config.file=/prometheus-data/prometheus.yml]
    links:
      - gw
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
